### PR TITLE
Feature/team

### PR DESCRIPTION
**Pull request by jschirrmacher**
I re-organized the blog articles to be in a sub folder and the pictures to have a folder of their own.
Additionally, there are `team` pages now, to show some information about blog article authors.

This change requires to use `authorPage` meta attributes in the blog pages, instead of the current `author` attributes.

### CODE REVIEW

**Comment by jschirrmacher** [comment]
@vaalto please have a look at this PR, it is not yet ready for production, but I wanted to let you know what I plan to do.

**Comment by vaalto** [comment]
I took a look of your commits and idea to make team page. Sounds like a plan! Just let me know when we're going to use the author pages.

**Comment by vaalto** [comment]
One question about Jim Kalbach's article: the link to online magazine "box and arrows" didn't work. Maybe we should remove the Link?

**Comment by jschirrmacher** [comment]
I just checked it and found, that our link is simply wrong. Instead of http://www.boxandarrows.com we need http://boxesandarrows.com (see http://boxesandarrows.com/authors/jameskalbach).

Although they write about User Experience, they don't use https... but that's another topic.

**Pull request merged**
